---
title: "Schedule"
subtitle: GEOG693 Open Data Science
author: "A Hessl"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Please check this schedule early and often - schedule will be adjusted based on the pace of our class.  
<br/>

### __Before You Come to Class__  
Please complete this before the first day of class.  
[Installing Software](./lectures/InstallingSoftware.html)    
<br/>

### __The Shell__

1) [Class Concept](./lectures/ClassConcept.html) _08/21/19_  
    + RStudio  
    + GitHub  

2) [Shell Basics](./lectures/ShellBasics.html) _08/23/19_   

4) [Files and Directories](./lectures/FilesDirectories.html) _08/28/19_  

5) [Wildcards, Pipes, and Filters](./lectures/WildcardsPipesFilters.html) _08/30/19_   

6) [Loops](./lectures/Loops.html) _09/04/19_  

7) [Accessing Data with `wget`](./lectures/wget.html)  _09/11/19_  

8) [Shell Scripts](./lectures/ShellScripts.html) _09/13/19_  

9) [Finding Things](./lectures/Find_grep.html)  _09/18/19_
    + `grep`  
    + `find`  


***  

### __Project Management and Collaboration__

1) [Version Control Using Git](./lectures/Git.html) _09/20/19_

2) [Collaboration and Sharing Using GitHub](./lectures/GitHub.html) _10/02/19_

3) [Project Management in R Studio](./lectures/RStudioProjMan.html) _10/04/19_

<br/>

### __Working with Data in R__  

1) [Intro to R](./lectures/RIntro.html) _10/09/19_

2) [Help in R](./lectures/RHelp.html) _10/16/10_

2) [Data Structures](./lectures/RDataStructures.html)  _10/16/19_

2) [Subsetting/Indexing Data](./lectures/RSubsetting.html)  _10/25/19_

3) [Data Frames](./lectures/RDataframes.html)  _10/23/19_

4) [Control Flow: If/Else](./lectures/RIfElse.html)  _10/30/19_

5) [Control Flow: Functions](./lectures/RFunctions.html) _10/30/19_

6) [Control Flow: Apply](./lectures/RApply.html)  _11/06/19_

7) [Control Flow: Apply_Loops](./lectures/RApply_Loops.html)  _11/08/19_

8) Plotting Using Base R  _11/08/19_

9) Plotting Using ggplot  _11/13/19_

10) APIs to Download Data  _11/15/19_

11) Editing a Package  _11/15/19_

#### __Acknowledgments__
_These pages were derived in part from:Benjamin Soltoff's MACS 30500 - [Computing for the Social Sciences](https://cfss.uchicago.edu/) at University, and from [Software Carpentry](software-carpentry.org), licensed under the CC BY-NC 3.0 Creative Commons_

