---
title: "ClassGitRepo"
author: "A Hessl"
date: "6/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's make a new directory for this class (~/GEOG693) and a new folder in that directory to contain lectures (~/GEOG693/lectures. This will become your first repository (aka 'repo'):

```{bash, eval=FALSE}
cd ~
mkdir GEOG693
mkdir GEOG693/lectures
```
		
Set your working directory to the newly created directory: 

```{bash, eval=FALSE}
cd ~/GEOG693/lectures
```

Now the magic - initialize your working directory as a git repository:
	
```{bash init, eval=FALSE}
git init
```

You now have a new repository created called ```/lectures```. Any files or folders that undergo changes in this repository can now be tracked with version control. 

Use the list files command in terminal to see that git has created a hidden directory within your new repo called .git: 

```{bash, eval=FALSE}
ls -a
```
Here, you are using the ```-a``` option for “all files.” Try it without the ````-a``` option, and you will see that the shell does not list the ```.git``` directory. This is because it is hidden. ```-a``` shows these hidden files. 
	
Check that your repository is set up correctly: 

```{bash git status}
git status
```

Any new folders created under ```/lectures``` will automatically be in the repository. That is, if you want a subdirectory, simply make the new directory within ```/lectures```; you do not need to initialize the sub-directory - in fact you don't want to do that! Initializing the sub directory can cause problems with the parent directory. Instead just allow that subdirectory to be tracked along with your other files and folders.
	