---
title: "Git"
author: "A Hessl"
date: "6/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#### This activity assumes you have already [installed and configured Git](./lectures/InstallingSoftware.html).

### Problem  
I built an awesome BMX bike from parts when I was 12.  I loved that bike - it was perfect.  But then I took it apart and I could not get it back together again.  If only I could roll back time to 1982, I could ride that perfect bike again. With Git, I can do just that. I can build and change scripts with confidence because I know that if I break a script, I can go back in time and grab the working version.

### What Is Version Control?
Version control is a tool for organizing and archiving changes to files and directories of files. This is essential to efficient coding as well as scientific collaboration. Version control negates the messy need for sending versioned files back and forth with collaborators via email or having folders filled with multiple edited files of the same type (e.g. Hessl_Paper, Hessl_Paper.1, Hessl_Paper_2015a, etc.). Version control is like the “undo” button on a word processor - you can always retrieve past versions, grab good chunks, and correct mistakes. But it's even better, because it can track all of the files in a directory (and its subdirectories). You can even have multiple versions being changed at the same time that eventually get merged back together again.

### Why Use Version Control?
Imagine Jess and a colleague, Jenny, are working on a new project that includes accessing raw data, editing files, running a script on those files, producing output, and then organizing that output using an additional analysis script.  You are going to split up some of the work so that Jenny writes the loops in each script and Jess does the quality control.  As the scripts build, each contributes, but both people need at least some of the parts working at any given time.  They need to be able to "break" the part they are working on while keeping the rest of the script working so that the other partner can do her job. And they also need to merge working parts together. OY!  It's not going to work to email stuff back and forth! Imagine all the versions. If you made a mistake and needed to go back - how would you know which version to go back to???

### _ENTER Git!_

### Terms/Commands  
*	__repository__ - a version control storage area where all commits are stored, including information about when, where, and who changed the file. A repository allows multiple users to share and edit information, while keeping track of each of those changes. Repositories can be _remote_ (GitHub) or _local_ (Git).  
*	__local repo__ - a repository that is kept on your local machine/workspace.  
*	__remote repo__ - a repository that is kept on a remote location, as in "the cloud".  
*	__commit__ - the act of recording a current file version in a repository, or, as a noun, the actual recorded group of changes to a file in a repository. Similar to a revision.   
*	__stage/unstage__ - a step before commit where files are kept in a sort of holding pen.  
*	__git__ - open-source version control system that can be managed from the Terminal.
*	GitHub - a central remote repository that serves as a central hub for collaboration between multiple users.
* __Git Client__ - a gui interface that allows you to work with git without the command line and with better visualization. RStudio has a built-in git client, but there are others like [GitKraken](https://www.gitkraken.com/).  
*	__push__ - to forward changes from a local repository on your computer to a remote repository.  
*	__pull__ - to forward changes from a remote repository to a local repository.  


### Basic Usage of Git  
#### Setting up a repository
Let's get started by making a repo in our working directory called _./Rivers_.

```{bash, echo=-1, eval=TRUE}
cd ../data
mkdir Rivers
cd Rivers
git init	
```

```git init``` initializes the folder ```~/Rivers``` as a repo. Any files or folders that undergo changes in this repository can now be tracked with version control. 

Use the list hidden files command (```ls -a```) in terminal to see that git has created a hidden directory within your new repo called ```.git```: 
```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
ls -a
```
Here, you are using the ```-a``` option for “all files.” Try it without the ````-a``` option, and you will see that the shell does not list the ```.git``` directory. This is because it is hidden. ```-a``` shows these hidden files. 
	
Check that your repository is set up correctly by checking the status: 

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git status
```


#### Tracking Changes: 
First, create a text file that you can work with. In your terminal, create a file called “WVRivers.txt” and populate the file with some names of rivers in West Virginia. Later, we will make and track changes to this text file. 

Now you can edit the file.  Find it in the Files tab of lower right RStudio IDE. Click on it and it will open in your RStudio text editor (upper left). Let's add some rivers to the file:

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
touch WVRivers.txt
echo "Cheat 
Monongahela
Dents Run
Deckers Creek
Blackwater River 
Tygart River
Wheeling Creek
Kanawha River
New River
Big Sandy Creek
Elk" > WVRivers.txt
```


To check the status of ```WVRivers.txt``` in your git repository, use:
```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git status
```

#### Make an Initial commit
This tells you that WVRivers.txt is an “untracked file.” This means that git isn’t keeping track of the file via version control. We have to tell git which files we want to track. To do this, use git add: 

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git add WVRivers.txt
git status
```

Note that the changes to WVRivers.txt still need to be committed with a message:

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git commit -m "Started list of West Virginia rivers"
```

Using the ```-m``` option with ```git commit``` gives you the opportunity (required!) to add a notes message to your commit. This is an essential, brief comment that allows you and collaborators to remember what changes you made and why. 

Run git status again: 
```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git status
```

This indicates that everything is up to date and committed correctly. 

Let’s say that you now wanted to go back into your ```WVRivers.txt``` and make changes. Open ```WVRivers.txt``` and add “River” after Cheat, Monongahela, and Elk. 

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
touch WVRivers.txt
echo "Cheat River
Monongahela River
Dents Run
Deckers Creek
Blackwater River 
Tygart River
Wheeling Creek
Kanawha River
New River
Big Sandy Creek
Elk River" > WVRivers.txt
```
When you check git status, you will see that changes were made.

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git status
```

#### Viewing Changes with ```git diff```  
You can see which changes were made before adding and committing the changed file. 

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git diff
```


> Challenge: What do all the colors and symbols mean?

Assuming you want to keep the change, you need to use ```git add``` and ```git commit``` to fully save the changes:

```{bash, echo=-1, eval=TRUE}
cd ../data/Rivers
git add WVRivers.txt
git commit WVRivers.txt -m 'Added River to Monongahela, Cheat, and Elk'
```

Now, assume you show your list of rivers to someone else, and they are disappointed that certain rivers were not included. Open up WVRivers.txt and add the following rivers after the last line: 

```
Ohio River
Greenbrier River
South Branch Potomac River
Scotts Run
```
```{bash, echo=F, eval=TRUE}
cd ../data/Rivers
echo "Cheat River
Monongahela River
Dents Run
Deckers Creek
Blackwater River 
Tygart River
Wheeling Creek
Kanawha River
New River
Big Sandy Creek
Elk River
Ohio River
Greenbrier River
South Branch Potomac River
Scotts Run" > WVRivers.txt
```
> Challenge: How can you check that the changes were made and recognized as changes?

Finally, finalize your changes using: 

```{bash, echo=-1, eval=T}
cd ../data/Rivers
git add WVRivers.txt
git commit -m 'added four more rivers to the list'
```

It is a good idea to check git status again, and as much as possible, to confirm the changes are committed. 


#### Version Control History using ```git log```
You can check your entire version control history by using: 

```{bash, echo=-1, eval=T}
cd ../data/Rivers
git log
```

```git log``` lists all changes made with essential information, including who made changes, when changes were made, and what the changes were. Note that the “Author” information will display the information set up at the beginning when you used git config.  

#### View and Restore Past Commits - Travel Back in Time!!!

There are 3 ways to explore past commits: 

1.	```git diff HEAD~2 WVRivers.txt```
		
This shows the difference between the most recent (```HEAD```) and 2 commits prior (~2).  ```HEAD``` always refers to the most recent, while the ~N notation to the N previous commits.
	
	2. ```git show HEAD~2 WVRivers.txt```
Instead of printing difference, git show simply shows what changes were made 2 commits prior, which in this case was the first commit.

	3. ```git diff 67ef9162ff65c8b3c57eeb85b1979000e26489ca WVRivers.txt```
This will use the unique 40-digit commit identifier (you can see these by calling git log) to show the difference between commits. Since 40 is a lot of digits, you can also abbreviate and usually get the same results:

		```git diff 67ef9162 WVRivers.txt```

Suppose that somebody accidentally puts a non-West Virginia River in your file, and overwrites it. Open up your WVRivers.txt and type “Wabash River” under “Blackwater River”

```{bash, echo=F, eval=TRUE}
cd ../data/Rivers
echo "Cheat River
Monongahela River
Dents Run
Deckers Creek
Blackwater River 
Wabash River
Tygart River
Wheeling Creek
Kanawha River
New River
Big Sandy Creek
Elk River
Ohio River
Greenbrier River
South Branch Potomac River
Scotts Run" > WVRivers.txt
```

Now add and commit:
```{bash, echo=-1, eval=T}
cd ../data/Rivers
git add WVRivers.txt
git commit -m "The Wabash River might be in West Virginia"
git log
```

Somebody put the Wabash River in my list of West Virginia Rivers! But, being a savvy geographer, you know the Wabash River is in Indiana, not West Virginia. Therefore, you want to restore WVRivers.txt to a previous and correct version. You can do this by using ```git checkout``` and the same naming convention described before (```HEAD~N```):

```{bash, echo=-1, eval=T}
cd ../data//Rivers
git checkout HEAD~1 WVRivers.txt
```

If you open WVRivers.txt in the text editor, what do you see?  Which version of the list is now presented? If you are satisfied that is the most up to date (correct) version, then add and commit.

```{bash, echo=-1, eval=T}
cd ../data/Rivers
git add WVRivers.txt
git commit -m "Nope! Wabash River is in Indiana"
git log
```


#### Branching
What if you want to completely break the BMX bike to see if you can create a whole new drive train?  It's scary - what if you can't get it back together again?  No worries, you can use branching to isolate development work without affecting other branches in the repository. Each repository has one default branch and can add multiple other branches. You can merge a branch into another branch using a merge.

You should use branches to:  
*	Develop new features   
*	Fix bugs  
*	Safely experiment with new ideas  

Be sure to branch if you are going to do anything that compromises the working parts of a script. Especially branch when working with others - it's the polite thing to do.

Let's make a new branch for Iowa Rivers and then do a checkout so that we are working on that branch.
```{bash, echo=-1, eval=T}
cd ../data/Rivers
git branch IARivers
git checkout IARivers
```

Now let's do a couple of commits on that branch.

Create a new text file for IARivers.  Add some rivers. 
```{bash, echo=F, eval=TRUE}
cd ../data/Rivers
touch IARivers.txt
echo "Mississippi River
Des Moines River
Beaver River
Peas Creek
Boone River
Skunk River
Missouri River" > IARivers.txt
```
Add some more WV Rivers to its ```.txt``` file:
```{bash, echo=F, eval=TRUE}
cd ../data/Rivers
echo "Mississippi River
Des Moines River
Beaver River
Peas Creek
Boone River
Skunk River
Missouri River 
West Fork
Buffalo Creek" > IARivers.txt
```

Add and commit the files (you can do them at the same time or use a wildcard)

```{bash, echo=-1, eval=F}
cd ../data/Rivers
git add IARivers.txt WVRivers.txt
git commit *Rivers.txt -m "Added new file of Iowa Rivers"
```

What happens when you do a git status?

Switch back to the master branch:
```{bash, echo=-1, eval=T}
cd ../data/Rivers
git checkout master
```
To see the current branches, try:

```{bash, echo=-1, eval=T}
cd ../data/Rivers
git show-branch
```

We are satisfied with our changes and have decided we want to keep the new Iowa file. How do we merge it all back together?

```{bash, echo=-1, eval=T}
cd ../data/Rivers
git merge IARivers
```

#### Removing a Repo
One day you might want to remove an old repo.  To do this you will need to eliminate not just the files, but also the hidden files.  You can do this using rm with -rf flag from within the repo. This will eliminate the .git folder which holds all the changes and other git stuff. Don't actually run this as we want to keep the repo!

Remove the _/Rivers_ git repo, but still keep all your files:
```{bash rm rivers}
cd ../data/Rivers
rm -rf .git
ls -a
```
```{bash, echo=F}
cd ../data
rm -r Rivers
```

#### RStudio and Git  
Next time, we will use the Git client in the RStudio IDE to work with git.  To make get this feature work in RStudio, you must be working in an R-project with version control.

### Key Points  
*	Git is a local version control system, the kid sister of GitHub, where you can keep track of changes to scripts, data, etc.  
*	__repo__ - Like a depot, but for scripts and data on a single project where all commits are stored, including information about when, where, and who changed the file. Repositories can be remote or local.  
*	__commit__ - the act of recording a current file version in a repo. It's a two-step process involving add then commit.  
*	__branch__ - each repo contains a ```master``` branch where everything should work. To isolate development work without affecting other branches in the repository create a new branch. Branches can be merged back together when the new stuff is functioning.  
* __diff__ - difference between two versions of a file or project.  

