---
title: "GitHub"
author: "A Hessl"
date: "6/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Problem  
You are now able to break your BMX bike as many times as you want, but still go back to 1982 and have a working bike.  You can add parts to your new bike by making ```commit``` or fix sections of your old bike using ```branch``` and ```merge```.  You can do all of this from the bash shell.

What if you want to let someone else break your bike and build a better version, while at the same time keeping your working bike…working? This is the nature of open-source coding and why GitHub and similar repositories have made so much possible in so little time.

### Tools/Terms  
*	__remote repo__ - like a local repo, but in the cloud and available for others to clone  
*	__fork__ - create a copy of a remote repo and download it to your local computer  
*	__git pull__ - pulls the most recent changes from the remote repo to your local repo  
*	__git push__ - pushes your changes from local repo to the remote repo  
*	__conflict__ - when two sets of changes conflict with each other.  These will need to be resolved before you can make a new commit.  

### GitHub
All of our work in Git so far is useful to track your own versions of files.  Sometimes, you just want to git back to a previous version. You can do this by viewing the log plus careful ```-m``` commit message to remind you of what you changed in that version.  This is extremely useful in coding as you can easily break your script, just like I broke my BMX bike.  But what if you are working with other people - like a whole world of collaborators? How does "open source" work anyway?

[GitHub](https://www.github.com) (as opposed to plain old Git) is a commonly used collaborative site where multiple users can fork or clone repositories to their local workspace, make changes, add/commit those changes, push them back to the remote repo and view logs etc. The primary benefits of using a remote repository include the ability to have a central hub for your version control that can be accessed by many collaborators, even when separated by time and distance. 

### Create a Remote Repo
First be sure you have already signed up for a free account at github.com. For this in class activity, you will need to team up with one other classmate.

Once you are logged into GitHub with your new account, you can create a new repository by clicking on the “+” icon in the upper right-hand corner of the web page. Designate one of your 2 teammates (call her Jane) to create this repository and call it ```Rivers```, just like the repository you created on your computer. Leave the setting at “Public” and click “Create!”  For now, __do not__ click the box for creating ```ReadMe file```.  DO NOT MAKE A FIRST COMMIT.  If you do, your local repo and your remote repo will be in conflict.  We will get to that later!

### Link Your Local Repo to the Remote Repo
Now you have a remote repository called ```Rivers```, but it is empty. Next, we need to link your local Rivers repository with the remote on GitHub so you can share changes with collaborators. On GitHub, you will see a unique identifying web link describing your remote repository. Jane should copy this link. It should look something like:
```https://github.com/JaneSmith/Rivers.git```

### RStudio Client for GitHub
RStudio allows us to connect directly with GitHub through R-Projects.  An ```R-Project``` is a directory that contains all your scripts, data, functions, and output.  The extension is ```.Rproj```. To start a new project that will link to our Rivers GitHub repo, click on ```File-New Project``` and select ```Version Control``` with ```Git```.  Give your new R-Project a name (```RiversProj```) and place it in your root directory. 

Now Jane should connect to her remote repo by pasting the URL from GitHub into the ```Repository URL```.

Ensure the remote link is worked by typing:

```{bash, echo=-1, eval=T}
cd ~/RiversProj
git remote -v
```

#### Is RStudio Having Trouble Connecting to GitHub?
Try the following:  
* Restart RStudio and try again.  
* At the bash terminal, type:  
    + ```git remote add origin https://github.com/mygitusername/myrepo.git```  
    + ```git push -u origin master```  
* Still having issues? All Git-R questions can be answered here: https://happygitwithr.com/ especially see [Chapter 13](https://happygitwithr.com/rstudio-see-git.html)

### Jane Makes a Change
Jane should now move the ```Rivers.txt``` file to the new project and then tell Git to track it.  We can do this from either the bash terminal or from RStudio's Git interface.

From bash:
```{bash, eval=F}
mv ~/Rivers/Rivers.txt ~/RiversProj/Rivers.txt
cd ~/RiversProj
git add Rivers.txt
```
From RStudio:
Under the files tab (lower right), click the box for the file you want to move, then click on the cog wheel icon and select ```Move...```. 

#### Jane Adds Files
Now ```add``` new files in Git by clicking on the Git tab (upper right).  In yellow are the new untracked files.  Click on both the ```.RProj``` and on the ```Rivers.txt``` files. They should now have a green A denoting that they have been added. This is equivalent to ```git add```. 

#### Jane Is Not Afraid of Committment
Click on ```Commit```.  Now you can add a commit message and observe any changes you have made since the last commit.  Since this is your first commit everything is new and there are no conflicts!

When Jane is done typing her message, she clicks ```Commit```

### Push First Changes
The next bit is really easy in RStudio. Jane will now ```push``` her changes to the remote repository on GitHub. Push is similar to commit. The only difference: when you push, you are sending changes to a remote repository, and when you commit, you are sending changes only to the local repository. For RStudio, click on the green arrow.

If Jane would like to use bash shell:

```{bash, echo=-1, eval=TRUe}
cd ~/RiversProj
git push origin master
```

At this time, go back over to GitHub and check that ```WVRivers.txt```, along with comments and changes, has now arrived in your remote repository! Now others can access and make changes to speed up the collaboration process. 

#### Cloning
Jane, who created the Rivers repository, now needs to invite her partner, Tom, to collaborate on the remote repository. Click the ```Settings``` tab in the upper right of your repository, and then click ```Collaborators```. In the space for ```Add collaborator``` Jane must enter Tom’s user name or email address associated with his account and click add collaborator.  

Once the Jane has sent an email collaboration request, Tom can accept the button in the email.  Tom will be redirected to GitHub notifications: https://github.com/notifications, where he can accept access to the ```Rivers``` repository.  Tom will need to hit the ```clone or download``` button to get the URL for the remote repo, for ex:
	https://github.com/JaneSmith/Rivers.git

Now Tom needs to copy the remote repository to his local machine, a step called cloning. He can do this in several ways:  

* From Rstudio by creating a new project (as above)   
* From bash:  
```git clone https://github.com/ahessl/Rivers.git ~/TomsRiversProj/```  


#### Tom Makes a Committment
Next, Tom can start making changes to files in the repository. Make sure that Tom's working directory is the cloned repository, and then make a new text file in that directory called `INRivers.txt` populated with the names of rivers in Indiana:

```{bash}
cd ~/Rivers
touch INRivers.txt
```
Open your new text file and add these rivers:  

Wabash River  
Muscatatuck River  
Fall Creek  
St. Joseph River  
White River  
Tippecanoe River  
Whitewater River   
Driftwood River  
Ohio River  
Iroquois River  
East Fork White River  

Now add and commit this new file to the repository using the push and commit commands (or using RStudio) 
```{bash eval=FALSE, include=FALSE}
cd ~/Rivers
git add INRivers.txt
git commit -m “Added names of some rivers in Indiana to your list of state rivers”
```

IMPORTANT NOTE: You have only committed these files to your local repository.  You still need to push them to the online master at GitHub.  Either push using the up arrow in RStudio or push from bash using ```git push origin master```

Check back in on the owner’s remote repository at GitHub - you should see a new file called INRivers.txt. 

Jane can now pull the Tom’s changes from the remote repository to her own local and make additional changes, either with RStudio or ```git pull origin master```

At this point, all three repositories, i.e. the Jane's GitHub repo, and Jane and Tom's local repositories are now in sync. If only it were so easy in relationships...


#### How to Resolve Merge Conflicts

What if Tom and Jane modify the same file in different ways?  This creates a conflict. To see what happens when you have a file in conflict, you and your partner should both modify WVRivers.txt, then attempt to commit and push the revised files to the remote repo. 

Git should throw an error like:
```{bash, eval=F}
cd ~/Rivers
git push origin master
```
To https://github.com/ahessl/Rivers.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/ahessl/Rivers.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Git rejects the push because it detects that the remote repository has new updates that have not been incorporated into the local branch. What we have to do is pull the changes from GitHub, merge them into the copy we’re currently working in, and then push that. Let’s start by pulling:

```git pull origin master```
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/ahessl/Rivers
 * branch            master     -> FETCH_HEAD
   d3774b9..398e401  master     -> origin/master
Auto-merging WVRivers.txt
CONFLICT (content): Merge conflict in WVRivers.txt
Automatic merge failed; fix conflicts and then commit the result.


To fix the conflict, I have to edit WVRivers.txt. If you open your conflicted file in a text editor, you will note that it now contains some strange symbols that denote the kinds of conflicts.

To see the beginning of the merge conflict in your file, search the file for the conflict marker <<<<<<<. When you open the file in your text editor, you'll see the changes from the HEAD or base/master branch after the line <<<<<<< HEAD. Next, you'll see =======, which divides your changes from the changes in the other version followed by >>>>>>> BRANCH-NAME if there was a new branch. 

Decide if you want to keep only your changes, keep only the other version's changes, or make a brand new change, which may incorporate changes from both branches. Delete the conflict markers <<<<<<<, =======, >>>>>>> and make the changes you want in the final merge. Save this file using the same name, in my case WVRivers.txt.

Now check the status:

$ git status
On branch master
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

	modified:   WVRivers.txt

I am ready to commit, but when I do, Git throws another error:

fatal: cannot do a partial commit during a merge.

A partial commit is when you are only committing some files, not all the files in a repo.  If you got this error, you can add an -i flag that lets you commit a single file.

$ git commit WVRivers.txt -i -m "resolved conflict by including all rivers" 
[master 0500531] resolved conflict by including all rivers
Amys-MacBook-Pro-7:Rivers amyhessl$ git status
On branch master
nothing to commit, working tree clean


Don't forget to PUSH!

$ git push origin master
Counting objects: 19, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (19/19), 1.70 KiB | 0 bytes/s, done.
Total 19 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 1 local object.
To https://github.com/ahessl/Rivers.git
   398e401..0500531  master -> master

Ahhhh.  All good.

### Fork the Homework

### Push the Homework

What is GitHub Flow?
•	Anything in the master branch is deployable
•	To work on something new, create a descriptively named branch off of master (ie: CA-rivers)
•	Commit to that branch locally and regularly push your work to the same named branch on GitHub
•	When you need feedback or help, or you think the branch is ready for merging, open a pull request. Pull request is performed at GitHub.com
•	After someone else has reviewed and signed off on the feature, you can merge it into master using merge pull request at GitHub.com
•	Once it is merged and pushed to ‘master’, you can and should deploy immediately





Further Reading
	Git Basics: https://git-scm.com/book/en/v2/Getting-Started-Git-Basics

	Software Carpentry Version Control Tutorial: http://swcarpentry.github.io/git-novice/

	Git cheatsheet: https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf

	Using git in R: http://happygitwithr.com



