---
title: "Working with Text Files"
author: "A Hessl"
date: "5/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Problem
Demetrius' advisor gave him a folder full of files produced by a remote data logger that he is supposed to analyze.  The files are named 'data_file_1', 'data_file_2', etc.  He notices that there is no extension and excel won't open the file.  How can Demetrius figure out what format the files are in and find a way to analyze the data?

### Questions

*	What is a text file?  
* How are text files different from excel files?
*	How can text files be opened and edited?  
* What's the difference between .csv, .txt, tab-delimited and other kinds of text files?
*	How can I create my own text files?

### Objectives
*	Recognize different kinds of text files.  
* Compare several different text file editors.  
*	Examine the anatomy of different kinds of text files.  
*	Learn to write, edit and save a text file.  

### Tools/Terms
*	__Text file__ - aka flatfile, is a computer file structured as a sequence of lines of text. These lines of text are human readable and machine readable. This is in opposition to the other major type of computer file, binary (not human readable).
* __Plain text__ - content of a text file without formatting, for example, does not contain bold or italic.
* __ASCII__ - character set most commonly used for text files in English language. Other character sets include Unicode, UTF-8
*	__POSIX__ - the Unix text file format.
*	__Text editor__ - computer program that edits plain text. Ex: Nano, Notepad, TextEdit, Atom
*	__Delimiter__ - one or more characters that separate independent regions/items in plain text. Ex: comma, space, tab.  But others can be defined and used.


### Anatomy of a Text File
Double click on MorgPre.txt and MorgPre.csv files located in /data.

* What program opened the files?  
* What are they?  
* How do they differ?  
* How is each delimited?  
* Which is the better format?  
* What happens if you open them in excel?  

>__Challenge: What is MorgPre (with no extension)? Why are extensions important?__


### Key Points
*	Text is a machine and human readable format that has remained stable since the beginning of computing.  
*	Text files are the holders for scripts (code) and data.  
*	Many data files, especially from government sources, are stored as 'raw' data in text files.  
*	Text is usually delimited by a comma, space or other separator.  
*	Many text editors will do the job of viewing, searching and editing text files.  
* RStudio includes a text editor (upper left window).


